version: 2

sources:
    - name: staging
      database: personal-projects-420210
      schema: uk_real_estate_analytics_bq_dataset_personal_projects_420210
      tables:
        - name: uk_real_estate_analytics

models:
    - name: stg_real_estate_model
      description: >
        Price Paid Data tracks property sales in England and Wales submitted 
        to HM Land Registry for registration.
      columns:
        - name: transaction_unique_identifier
          description: >
            A reference number which is generated automatically recording each 
            published sale. The number is unique and will change each time a 
            sale is recorded.
        - name: price
          description: Sale price stated on the transfer deed.
        - name: date_of_transfer
          description: Date when the sale was completed, as stated on the transfer deed.
        - name: postcode
          description: >
            This is the postcode used at the time of the original transaction. 
            Note that postcodes can be reallocated and these changes are not reflected 
            in the Price Paid Dataset.
        - name: property_type
          description: >
            A code indicating the property type.
            D = Detached,
            S = Semi-Detached,
            T = Terraced,
            F = Flats/Maisonettes,
            O = Other
        - name: old_new
          description: >
            Indicates the age of the property and applies to all price paid transactions, 
            residential and non-residential.
            Y = a newly built property,
            N = an established residential building
        - name: duration
          description: >
            Relates to the tenure:
            F = Freehold,
            L = Leasehold
        - name: paon
          description: Primary Addresable Object Name. Typicall the house number or name.
        - name: saon
          description: >
            Secondary Addressable Object Name. Where a property has been divided into 
            separate units (for example, flats), the PAON (above) will identify the 
            building and a SAON will be specified that identifies the separate unit/flat.
        - name: street
        - name: locality
        - name: town_or_city
        - name: district
        - name: county
        - name: is_update
          description: > 
                Indicates if the record is an update to an exisiting record or not. Y = Yes or,
                N = No.
        - name: postcode_outward_code
          description: Postcode outward district code.
          tests:
              - relationships:
                  to: ref('postcodes_lookup')
                  field: postcode
                  severity: warn
