version: 2

models:
    - name: dim_location_info
      description: >
        Location info such as easting, northing, latitude, longitude
        town, and region values for various UK postcodes.

    - name: fact_real_estate_market
      description: >
        Data on real estate transactions carried out in the UK from
        1995 to the present day (Newest version of data available)
      columns:
        - name: transaction_id
          data_type: string
          description: "Unique identifier for each transaction"

        - name: price
          data_type: float
          description: Price paid for the property
        
        - name: date_of_transfer
          data_type: date
          description: Date the transaction was recorded.
        
        - name: postcode
          data_type: string
          description: Postcode of the property
        
        - name: property_type_description
          data_type: string
          description: Description of the property type.
        
        - name: property_age_description
          data_type: string
          description: Description of if the property is newly built or not.
        
        - name: tenure_type
          data_type: string
          description: The tenure type of the property.